---

# we have to remove python-requests and pyyaml installed by distutils
# cause python-requests conflicts with requests lib installed by pip during docker-compose install
# and pyyaml conflicts with oslo.config that is used for kolla-deployer
- name: remove packages installed by distutils on RedHat families
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - python-requests
    - PyYAML
  register: res
  retries: 5
  until: res is success
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

# NOTE: Do not use easy_install for RedHat. There is a bug that might cause
# easy_install to hang:
# https://github.com/ansible/ansible/issues/15769
# https://bugzilla.redhat.com/show_bug.cgi?id=1702797
# Use shell to intall pip for RedHat to work around the bug

- name: check if pip present
  shell: pip2 --version
  ignore_errors: true
  register: pip_check
  when: ansible_distribution_major_version|int == 7

- name: Install pip
  block:
    - name: Download pip
      get_url:
        url: "{{ get_pip_url }}"
        dest: /tmp/get-pip.py
        force: yes
        mode: 0400
    - name: Install pip
      shell: "python /tmp/get-pip.py 'pip==20.1'"
      become: yes
  when:
    - ansible_distribution_major_version|int == 7
    - pip_check.rc != 0

# if pip was already there then it should be updated if it's version is less than 10.0
# (it doesn't support python2/3 metadata)
- name: upgrade pip
  pip:
    name: 'pip>=19,<21.0'
  become: yes
  register: res
  retries: 5
  when: ansible_distribution_major_version|int == 7
  until: res is success

- name: check if pip3 present
  shell: pip3 --version
  ignore_errors: true
  register: pip_check
  when: ansible_distribution_major_version|int == 8

- name: Install python3-pip on rocky8
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
    - python3-pip
  when:
    - ansible_distribution_major_version|int == 8
    - pip_check.rc != 0

- name: upgrade pip on rocky8
  shell: pip3 install pip --upgrade
  when: ansible_distribution_major_version|int == 8
