- name: update contrail k8s_cni image
  shell: "docker pull {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}"
  register: res
  retries: 5
  until: res.rc == 0
  with_items:
    - contrail-kubernetes-cni-init
  when:
    - contrail_configuration.UPDATE_IMAGES is undefined or contrail_configuration.UPDATE_IMAGES != false
    - roles[instance_name].k8s_node is defined
