- name: Create container host group
  hosts: localhost
  connection: local
  gather_facts: yes
  pre_tasks:
    - name: Set orchestrator if not passed
      set_fact:
          contrail_configuration: "{{ contrail_configuration | default({}) | combine({'CLOUD_ORCHESTRATOR': orchestrator if orchestrator is defined else 'openstack'}) }}"
      when: contrail_configuration is not defined or contrail_configuration.CLOUD_ORCHESTRATOR is not defined
    - name: Expose instances
      set_fact:
          instances: "{{ instances }}"
      when: hostvars['localhost']['instances'] is undefined
  roles:
    - pip
    - contrail_deployer
    - { role: windows_deployer, when: provider_config.bms_win is defined }
    - { role: kolla_deployer, when: contrail_configuration.CLOUD_ORCHESTRATOR == 'openstack' }
  vars_files:
    - "{{ config_file }}"

- name: Configure instance(s)
  hosts: container_hosts
  gather_facts: yes
  pre_tasks:
    - name: A bugfix for Ubuntu 20.04
      set_fact:
        ansible_os_family: "Debian"
      when: ansible_os_family is undefined
  roles:
    - pip
    - instance
    - docker
  vars_files:
    - "{{ hostvars['localhost'].config_file }}"
  environment:
    - https_proxy: "{{ global_configuration.HTTPS_PROXY if global_configuration.HTTPS_PROXY is defined else contrail_configuration.HTTPS_PROXY | default('') }}"
    - http_proxy: "{{ global_configuration.HTTP_PROXY if global_configuration.HTTP_PROXY is defined else contrail_configuration.HTTP_PROXY | default('') }}"
