- name: update contrail mesosphere cni image
  shell: "docker pull {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}"
  register: res
  retries: 5
  until: res.rc == 0
  with_items:
    - contrail-mesosphere-cni-init
  when:
    - contrail_configuration.UPDATE_IMAGES is undefined or contrail_configuration.UPDATE_IMAGES != false
    - roles[instance_name].mesos_agent_private is defined or roles[instance_name].mesos_agent_public is defined
